add_newline = true

[battery]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 1_000
show_notifications = true
min_time_to_notify = 30_000

[git_commit]
tag_disabled = false

[package]
disabled = true

[status]
disabled = false

[username]
show_always = true
